### ISSUE TITLE
Relative links in pages

### ISSUE THREAD

**Issue by zspri** [dragon-drop-scratch/dragon-drop-scratch.github.io#94]
There are several links that use "./" or "../".
They should be removed, as they can cause lots of errors.

For example:
```html
<link rel="stylesheet" href="./Essentials/style.css>
```
shouldn't be used, instead use:
```html
<link rel="stylesheet" href="https://dragon-drop-scratch.github.io/dragon-drop-www/Essentials/style.css">
```
It may be longer, but it's worth it if you have to move pages around.

**Comment by coke11** [comment]
The first thing †hat comes to mind when I see this is "When we move this to our servers will we have to change every single link again? The question we need to ask ourselves is "Is it better to have it so that if you change the format you don't need to go around changing it but when you change servers you do or vice versa? My vote is just leave it as it is, and if there is a problem, this cane be a first troubleshooting step.

**Comment by zspri** [comment]
@coke11 True, but we need a more organized site in general.

**Comment by coke11** [comment]
In my personal opinion <link rel="stylesheet" href="./Essentials/style.css> is much cleaner than <link rel="stylesheet" href="https://dragon-drop-scratch.github.io/dragon-drop-www/Essentials/style.css">. Am I understanding this wrong?

**Comment by zspri** [comment]
Not necessarily, but it _is_ your opinion. Maybe http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/, https://yoast.com/dev-blog/relative-urls-issues/, and https://www.navegabem.com/absolute-or-relative-links.html would help?

**Comment by card100** [comment]
I agree with coke
